### ISSUE TITLE
界面加载很慢

### ISSUE THREAD

**Issue by Peterae** [yizhaorong/intranet_app_manager#1]
挺方便的，就是界面加载很慢

**Comment by yizhaorong** [comment]
你指的是 Github 的界面，还是项目界面。Github 页面中 README 中加载了不少图片，所以可能会慢一些，已经做了图片压缩，网速不佳可能也是没办法。

**Comment by Peterae** [comment]
我指的是项目界面，我部署测了下，加载列表都要好久，点编辑进入详情也很慢，但看日志也没报错，不知道什么原因？

**Comment by yizhaorong** [comment]
你是直接部署在服务器上还是本机，你可以先试一下本机部署一个。看看是不是速度很慢。直接访问 127.0.0.1 来访问。

**Comment by Peterae** [comment]
是的，就是本机，但是没换 SSL 证书，这个不影响吧？你那边不慢吗？

**Comment by yizhaorong** [comment]
不影响的，只要 iOS 安装的时候需要证书。我本地很快，内网服务器也没有出现你说的慢的问题。你数据库你连的也是本地的吗？你也可以把代码下载去调试一下，看看哪里有问题

**Comment by Peterae** [comment]
数据库也是本机，那我再试试！

**Comment by Peterae** [comment]
跟踪了下发现主要是重复读取配置文件导致过慢，我修改了下，其他地方没来得及看有没有可优化的地方，现在的速度能接受。
