### ISSUE TITLE
ios下载不了

### ISSUE THREAD

**Issue by LiuJiangc** [yizhaorong/intranet_app_manager#10]
ios上传上去，用安卓/苹果手机点击下载按钮，下载不了是什么问题

**Comment by LiuJiangc** [comment]
安卓的可以下载

**Comment by LiuJiangc** [comment]
是证书问题吗？自己建立了证书，安装证书后，ios的安装包，在苹果或者安卓2手机上都无法点击下载，安卓的安装包可以下载

**Comment by yizhaorong** [comment]
看文档，按文档建立证书。添加信任
