### ISSUE TITLE
您好，我想增加新的exe类型，请问要怎么做？

### ISSUE THREAD

**Issue by BruceCobb** [yizhaorong/intranet_app_manager#11]
有没有什么思路，是不是要写一个新的exeparser？

**Comment by yizhaorong** [comment]
是的

**Comment by BruceCobb** [comment]
我跑起来后什么都不做报 java.lang.NumberFormatException: null 错。

**Comment by yizhaorong** [comment]
完整的报错信息贴一下

**Comment by ddph** [comment]
> 有没有什么思路，是不是要写一个新的exeparser？

你实现exe上传了吗，我只能提取到exe的版本信息，提取的应用图标不全，你是如何提取exe文件的图标、应用名称的呢？
