### ISSUE TITLE
生成的链接地址

### ISSUE THREAD

**Issue by cn27001** [yizhaorong/intranet_app_manager#20]
建议使用独立的配置项或者根据url访问生成。
现在根据server.http.port server.domain生成，在实际使用时很麻烦 ，比如这个app运行在普通用户时，只能使用大端口 生成的url 也跟着此端口，但是应用是部署在nginx后面的。

**Comment by cn27001** [comment]
https 交给上次代理如nginx管理，这个程序就不要处理ssl了

**Comment by yizhaorong** [comment]
目前已支持通过访问host来生成路径
