### ISSUE TITLE
已经配置了数据库连接 但是启动的时候 还是报错

### ISSUE THREAD

**Issue by wutq** [yizhaorong/intranet_app_manager#22]
已经配置了数据库连接 但是启动的时候 还是报错

APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

Disconnected from the target VM, address: '127.0.0.1:11640', transport: 'socket'

**Comment by yizhaorong** [comment]
只支持MySQL，需要连接别的类型的数据库，需要自行接入
