### ISSUE TITLE
请教下

### ISSUE THREAD

**Issue by strivezheng** [yizhaorong/intranet_app_manager#3]
请问有数据库文件吗，我也一直想用java开发一个类似的平台，可以加个好友吗，一起交流下

**Comment by yizhaorong** [comment]
没有数据库文件，你把 JAVA 环境弄好，按教程中的步骤把数据库创建起来，这个工程使用的是 Hibernate 会自动把表建起来，如果你需要的话，启动完成之你就可以从 MySQL 中将建库和建表的语句导出了。
