### ISSUE TITLE
启动不起来

### ISSUE THREAD

**Issue by MuTongF** [yizhaorong/intranet_app_manager#4]
根本就启动不起来啊

**Comment by yizhaorong** [comment]
把报错信息贴出来

**Comment by MuTongF** [comment]
`Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

Disconnected from the target VM, address: '127.0.0.1:53372', transport: 'socket'

Process finished with exit code 0`

**Comment by yizhaorong** [comment]
嗯，你按照教程安装就可以，教程里面有说要装MySQL和创建相应的库，教程是以 Mac 为例的。其它的操作系统也可以查到相应的安装方式。
