### ISSUE TITLE
希望增加一个密码下载

### ISSUE THREAD

**Issue by jin123d** [yizhaorong/intranet_app_manager#5]
跑了一下效果很棒，先感谢作者。
再就是希望能加一个输入密码下载，谢谢。

**Comment by yizhaorong** [comment]
嗯，我思考一下是否需要加权限管理。因为考虑到内网部署，相对来说权限没那么重要。出于完整性考虑，后续我把权限这块加一下。

**Comment by jin123d** [comment]
@yizhaorong 我这边用接口上传apk，安装的时候经常有提示apk解析失败，你那里遇到过吗？

**Comment by yizhaorong** [comment]
没有，可以把你的APK传一份吗？我看看哪里有问题，放到百度网盘发链接就行

**Comment by jin123d** [comment]
@yizhaorong 是我apk签名配置有问题导致的，不好意思。
