### ISSUE TITLE
设置https后，首页进入是https,点击我的应用和预览应用就变成http了

### ISSUE THREAD

**Issue by LiuJiangc** [yizhaorong/intranet_app_manager#9]
请问需要怎么解决

**Comment by yizhaorong** [comment]
你是直接用代码运行的？

**Comment by LiuJiangc** [comment]
运行的是jar，部署到服务器，ssl证书是申请的

**Comment by LiuJiangc** [comment]
系统是Centos7

**Comment by yizhaorong** [comment]
你是想整个都用https吗？这个项目默认都是http的，如果你要全部用https的话，确实需要调整一下代码。我后面把这个改为配置类型的

**Comment by LiuJiangc** [comment]
是的，非常感谢您开源的程序，给了我很大的帮助。另外想问问运行您的源码需要安装什么开发工具/环境？

**Comment by LiuJiangc** [comment]
还有个问题需要反馈一下，远程连接Centos执行java -jar xxx.jar 之后，如果关闭连接，或者ctrl+c退出来的话，程序就结束了。

**Comment by yizhaorong** [comment]
JAVA环境JDK1.8，数据库MySQL，开发工具idea，想在后台运行可以用这样的命令。java -jar xxx.jar  &

**Comment by LiuJiangc** [comment]
谢谢。
